### PR TITLE
Make English version the default

### PR DESCRIPTION
**Pull request by juliecbd**

### CODE REVIEW

**Comment by reyoung** [comment]
Hello @juliecbd ,

There are several things need to know when contributing to book repository.

* Just like other repositories in `PaddlePaddle` organization, we are using [`pre-commit`](http://www.paddlepaddle.org/doc/howto/dev/contribute_to_paddle_en.html#using-pre-commit-hook) tools to check code style, automatically building HTML file, etc. Please install `pre-commit` tool first.
* In Book repository,  we using pre-commit to compile markdown file into html file. Here is the [regex pattern](https://github.com/PaddlePaddle/book/pull/316/commits/f8b38dab3a0ee2384b58e344eab69efb88dc96f6#diff-82c3b36709926de3a1b27bea0d8258ccR41) for matching files.
* Also, we are using `jinja2` template to compile the front page. [Here](https://github.com/PaddlePaddle/book/pull/316/commits/f8b38dab3a0ee2384b58e344eab69efb88dc96f6#diff-5772afbba143be6bb16ad22f390377df) is the template files of front pages.

And I just pushed another commit to your repository make `TravisCI` happy.

**Comment by luotao1** [comment]
Hello @juliecbd , #315 modify the install url in all chapters. After this PR, some urls may be dead. Please check all the urls in next PR.

**Comment by wangkuiyi** [comment]
Hi @luotao1, @juliecbd was asking, but I didn't understand your remind either. When you said "After this PR", were you referring to #315 or #316?  

I read that you fixed some URLs in #315. Does that imply that @juliecbd should redo #316 after #315 is merged, so that those fixed URLs appear in files renamed by #316?

**Comment by wangkuiyi** [comment]
@reyoung Thanks for the remind about pre-commit and the refresh of HTML files.

I have a question not tightly related with this PR -- should we include HTML files in this repo? Or, we can generate them when we deploy this repo to the server paddlepaddle.org?

**Comment by luotao1** [comment]
@wangkuiyi @juliecbd 
> Does that imply that @juliecbd should redo #316 after #315 is merged, so that those fixed URLs appear in files renamed by #316?

Yes, should redo #316 , since those fixed URLs will be disappeared.

**Comment by luotao1** [comment]
close due to #318

**Pull request closed without merging**
