### PR TITLE
Add serve API notes

### PR DESCRIPTION
**Pull request by helinwang**

### CODE REVIEW

**Comment by NorthStar** [comment]
Could you also say why to minimize confusion? It may also help to link to a place where they can find out how the usage for different models differ. Thanks!

**Comment by helinwang** [comment]
@NorthStar thanks! Done. The link I provided (https://github.com/PaddlePaddle/book/wiki/PaddlePaddle-Book-pretrained-model) for illustrating the API difference currently only have one HTTP request example, but I will make sure more will be added.

**Comment by NorthStar** [comment]
Lgtm after conflict resolution!

**Review by reyoung — APPROVED** [review]
LGTM

**Pull request merged**
