### PR TITLE
Refine the comments and the inference result format for "01.fit_a_line"

### PR DESCRIPTION
**Pull request by JiabinYang**
1. refined the comments 
2. refined the format of the inference result

### CODE REVIEW

**Comment by luotao1** [comment]
Do inference model contain `learning_rate_0` and `mean_0.tmp_0@GRAD`?

**Comment by JiabinYang** [comment]
yes @luotao1

**Comment by luotao1** [comment]
@Superjomn Should inference model contain `learning_rate_0` and `mean_0.tmp_0@GRAD`, maybe it is an error of high-level-python-api?

**Comment by reyoung** [comment]
@JiabinYang DO NOT COMMIT ANY BINARY FILES!!!

**Comment by JiabinYang** [comment]
latest commit:
1. delete the additional  binary files
2. refine the same problem in README.md

**Review by dzhwinter — APPROVED** [review]
The binary file cannot be tracked by CVS system like git, it's a good habit only keep minimal files in our repo. Please keep it clean. Thanks.

LGTM.

**Pull request merged**
