### PR TITLE
Fixing few typos in the English readme of Ch1 and Ch2

### PR DESCRIPTION
**Pull request by abhinavarora**

### CODE REVIEW

**Review by jacquesqiao — APPROVED** [review]
LGTM!

**Comment by jacquesqiao** [comment]
You should install a pre-commit to do the style check.~

**Review by jacquesqiao — CHANGES_REQUESTED** [review]
please install and pass pre commit first~

**Comment by abhinavarora** [comment]
@jacquesqiao All checks have passed. Could you please review again?

**Review by jacquesqiao — APPROVED** [review]
LGTM!

**Pull request merged**
