### PR TITLE
compatible with python3

### PR DESCRIPTION
**Pull request by tink2123**
fix : http://newicafe.baidu.com:80/issue/DLTP-1929/show?from=page

### CODE REVIEW

**Comment by JepsonWong** [comment]
LGTM

**Review by JiabinYang — APPROVED** [review]
LGTM

**Review by JiabinYang — CHANGES_REQUESTED** [review]
Why binary here， DO NOT ADD BINARY

**Review by JiabinYang — APPROVED** [review]
LGTM

**Pull request merged**
